worker_processes auto;
pid /run/nginx.pid;
error_log /dev/stderr;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format ingress '$remote_addr - $request_method $uri -> $status '
                       '[ingress_path=$http_x_ingress_path] '
                       '[content_type=$sent_http_content_type] '
                       '[body_bytes=$body_bytes_sent] '
                       '[referer=$http_referer]';
    access_log /dev/stdout ingress;

    sendfile on;
    keepalive_timeout 65;

    include /etc/nginx/servers/*.conf;
}
